#!/bin/zsh

# remove changes from local to avoid conflicts
cd ~/Documents/records
git stash
git stash clear

# open ssh
eval $(ssh-agent)
ssh-add ~/.ssh/id_github

# pull repo
git pull

# close ssh
ssh-agent -k
